import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";
const origins=new Set(["https://app.srccvde.com","http://localhost:5173","http://localhost:3000"]);
const cors=(req:Request)=>({"Access-Control-Allow-Origin":origins.has(req.headers.get("origin")||"")?(req.headers.get("origin")||""):"https://app.srccvde.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"});
const esc=(v:any)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]||c));
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((c||0)/100);
const b64=(bytes:Uint8Array)=>{let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)};
async function sha256(bytes:Uint8Array){const h=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function wrap(text:string,font:any,size:number,max:number){const words=text.split(/\s+/);const lines:string[]=[];let line="";for(const w of words){const test=line?line+" "+w:w;if(font.widthOfTextAtSize(test,size)<=max)line=test;else{if(line)lines.push(line);line=w}}if(line)lines.push(line);return lines}
async function makePdf(inv:any,items:any[],zelle:any){
 const pdf=await PDFDocument.create(),page=pdf.addPage([612,792]),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const W=612,margin=54,dark=rgb(.06,.08,.07),green=rgb(.12,.45,.27),muted=rgb(.38,.4,.39);let y=738;
 page.drawText("SRC",{x:margin,y,size:23,font:bold,color:dark});page.drawText("cvde",{x:margin+43,y,size:23,font:regular,color:dark});page.drawRectangle({x:margin,y:y-9,width:28,height:3,color:green});
 page.drawText("INVOICE",{x:W-margin-78,y:y+4,size:10,font:bold,color:muted});y-=60;
 page.drawText(inv.invoice_number,{x:margin,y,size:22,font:bold,color:dark});page.drawText(money(inv.total_cents-inv.amount_paid_cents),{x:W-margin-145,y,size:22,font:bold,color:dark});
 y-=20;page.drawText(inv.projects?.name||"SRCcvde project",{x:margin,y,size:10,font:regular,color:muted});const due=inv.due_at?new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric"}).format(new Date(inv.due_at)):"Upon receipt";page.drawText("Due "+due,{x:W-margin-145,y,size:10,font:regular,color:muted});y-=46;
 page.drawText("BILL TO",{x:margin,y,size:9,font:bold,color:muted});y-=18;page.drawText(inv.clients?.name||"Client",{x:margin,y,size:12,font:bold,color:dark});y-=15;if(inv.clients?.primary_contact_name){page.drawText(inv.clients.primary_contact_name,{x:margin,y,size:10,font:regular,color:dark});y-=14}if(inv.clients?.primary_email){page.drawText(inv.clients.primary_email,{x:margin,y,size:10,font:regular,color:muted});y-=14}y-=24;
 page.drawText("DESCRIPTION",{x:margin,y,size:9,font:bold,color:muted});page.drawText("AMOUNT",{x:W-margin-55,y,size:9,font:bold,color:muted});y-=10;page.drawLine({start:{x:margin,y},end:{x:W-margin,y},thickness:1,color:rgb(.85,.86,.85)});y-=22;
 for(const item of items){for(const line of wrap(item.description,regular,10,360)){page.drawText(line,{x:margin,y,size:10,font:regular,color:dark});y-=14}page.drawText(money(Number(item.quantity)*item.unit_amount_cents),{x:W-margin-80,y:y+14,size:10,font:bold,color:dark});y-=10}
 page.drawLine({start:{x:margin,y},end:{x:W-margin,y},thickness:1,color:rgb(.85,.86,.85)});y-=25;page.drawText("TOTAL",{x:W-margin-170,y,size:10,font:bold,color:muted});page.drawText(money(inv.total_cents),{x:W-margin-80,y,size:12,font:bold,color:dark});y-=45;
 if(zelle){page.drawRectangle({x:margin,y:y-72,width:W-margin*2,height:82,color:rgb(.95,.97,.95)});page.drawText("PAYMENT METHOD",{x:margin+16,y:y-18,size:8,font:bold,color:muted});page.drawText("Zelle for Business",{x:margin+16,y:y-38,size:12,font:bold,color:dark});page.drawText(zelle.payment_handle,{x:margin+160,y:y-38,size:12,font:bold,color:green});page.drawText("Include "+inv.invoice_number+" in the Zelle memo.",{x:margin+16,y:y-57,size:9,font:regular,color:muted});y-=102}
 if(inv.notes){page.drawText("NOTES",{x:margin,y,size:9,font:bold,color:muted});y-=17;for(const line of wrap(inv.notes,regular,9,500)){page.drawText(line,{x:margin,y,size:9,font:regular,color:dark});y-=13}}
 page.drawText("SRCcvde  |  app.srccvde.com",{x:margin,y:35,size:8,font:regular,color:muted});return new Uint8Array(await pdf.save())
}
Deno.serve(async(req:Request)=>{const headers=cors(req);if(req.method==="OPTIONS")return new Response("ok",{headers});const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...headers,"Content-Type":"application/json"}});
 try{const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))return json({error:"Unauthorized"},401);const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,resend=Deno.env.get("RESEND_API_KEY");if(!resend)return json({error:"Email service is not configured"},503);
 const caller=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:{user}}=await caller.auth.getUser();if(!user)return json({error:"Unauthorized"},401);const admin=createClient(url,service);const{data:member}=await admin.from("app_memberships").select("role,status").eq("user_id",user.id).maybeSingle();if(!member||member.status!=="active"||!["owner","admin","staff"].includes(member.role))return json({error:"Staff access required"},403);
 const{invoice_id}=await req.json();const{data:inv,error}=await admin.from("billing_invoices").select("*,clients(name,primary_contact_name,primary_email),projects(name)").eq("id",invoice_id).single();if(error||!inv)return json({error:"Invoice not found"},404);if(inv.status==="void")return json({error:"Voided invoices cannot be sent"},400);if(!inv.clients?.primary_email)return json({error:"Client email is unavailable"},400);
 const[{data:items},{data:methods}]=await Promise.all([admin.from("billing_invoice_items").select("*").eq("invoice_id",inv.id).order("sort_order"),admin.from("billing_payment_methods").select("*").eq("active",true).order("sort_order")]);const zelle=(methods||[]).find((m:any)=>m.method==="zelle");let pdfBytes:Uint8Array;
 if(inv.artifact_path){const{data,error}=await admin.storage.from(inv.artifact_bucket||"billing-invoices").download(inv.artifact_path);if(error||!data)return json({error:"Stored invoice PDF could not be loaded"},500);pdfBytes=new Uint8Array(await data.arrayBuffer())}else{pdfBytes=await makePdf(inv,items||[],zelle);const path=inv.client_id+"/"+inv.id+"/"+inv.invoice_number+".pdf";const hash=await sha256(pdfBytes);const{error:up}=await admin.storage.from("billing-invoices").upload(path,pdfBytes,{contentType:"application/pdf",upsert:false});if(up)return json({error:"Invoice PDF could not be archived"},500);const{error:meta}=await admin.from("billing_invoices").update({artifact_bucket:"billing-invoices",artifact_path:path,artifact_sha256:hash,finalized_at:new Date().toISOString()}).eq("id",inv.id).is("artifact_path",null);if(meta)return json({error:"Invoice archive metadata could not be saved"},500)}
 const due=inv.due_at?new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric"}).format(new Date(inv.due_at)):"Upon receipt";const html=`<div style="font-family:Arial,sans-serif;max-width:680px;margin:auto;color:#111"><div style="font-size:24px;font-weight:700;margin-bottom:30px">SRC<span style="font-weight:400">cvde</span></div><p>Hi ${esc(inv.clients.primary_contact_name||inv.clients.name||"there")},</p><h1 style="margin-bottom:4px">Invoice ${esc(inv.invoice_number)}</h1><div style="font-size:28px;font-weight:700">${money(inv.total_cents-inv.amount_paid_cents)}</div><p style="color:#666">Due ${esc(due)}</p><p>Your branded PDF invoice is attached and is also archived in your secure SRCcvde Billing workspace.</p>${zelle?`<div style="background:#f5f5f5;border-radius:12px;padding:20px;margin:24px 0"><b>Zelle for Business</b><div style="font-size:20px;font-weight:700;margin:6px 0">${esc(zelle.payment_handle)}</div><p style="margin:0">Include ${esc(inv.invoice_number)} in the Zelle memo.</p></div>`:""}<p>Questions? Reply to this email and we'll help.</p><p>— SRCcvde</p></div>`;const textBody=`SRCcvde Invoice ${inv.invoice_number}\nAmount due: ${money(inv.total_cents-inv.amount_paid_cents)}\nDue: ${due}\n${zelle?`Zelle for Business: ${zelle.payment_handle}\nInclude ${inv.invoice_number} in the memo.\n`:""}\nYour PDF invoice is attached and archived at https://app.srccvde.com/billing`;
 const rr=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resend}`,"Content-Type":"application/json"},body:JSON.stringify({from:"SRCcvde <hello@srccvde.com>",to:[inv.clients.primary_email],reply_to:"hello@srccvde.com",subject:`SRCcvde invoice ${inv.invoice_number} · ${money(inv.total_cents)}`,html,text:textBody,attachments:[{filename:inv.invoice_number+".pdf",content:b64(pdfBytes)}]})});const out=await rr.json().catch(()=>({}));if(!rr.ok)return json({error:out?.message||"Invoice email failed"},502);
 const now=new Date().toISOString();await admin.from("billing_invoices").update({status:inv.status==="paid"?"paid":"sent",client_visible:true,issued_at:inv.issued_at||now}).eq("id",inv.id);await admin.from("client_communications").insert({client_id:inv.client_id,project_id:inv.project_id,channel:"email",direction:"outbound",subject:`SRCcvde invoice ${inv.invoice_number}`,body:textBody,created_by:user.id,recipient_email:inv.clients.primary_email,delivery_status:"sent",provider:"resend",provider_message_id:out?.id||null,sent_at:now,client_visible:true});return json({sent:true,email_id:out?.id,to:inv.clients.primary_email});
 }catch(e){return json({error:e instanceof Error?e.message:"Unexpected error"},500)}});