import { FormEvent,useEffect,useMemo,useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { supabase } from './lib/supabase'

type Role='owner'|'admin'|'staff'|'client'
type Membership={role:Role;status:'invited'|'active'|'suspended'}
type Profile={full_name:string|null;email:string|null}
type Inquiry={id:string;name:string;email:string;company:string|null;project_type:string;budget_range:string;timeline:string;involvement:string;details:string;status:string;created_at:string;updated_at:string}
type Client={id:string;name:string;primary_contact_name:string;primary_email:string;status:string;drive_folder_id:string|null;created_at:string}
type Project={id:string;client_id:string;name:string;project_type:string|null;status:string;phase:string;progress:number;created_at:string}
type Note={id:string;body:string;created_at:string}
type Activity={id:string;entity_type:string;entity_id:string;action:string;summary:string;created_at:string}
type DocumentRow={id:string;client_id:string;name:string;category:string;state:string;client_visible:boolean;created_at:string;signature_kind?:'signature'|'acknowledgment'|null;executed_artifact_id?:string|null;drive_file_id?:string|null}
type ExecutedArtifact={id:string;document_id:string;storage_path:string;final_sha256:string;byte_size:number;generated_at:string;drive_sync_status:'pending'|'synced'|'failed'|'not_configured';drive_file_id:string|null;drive_error:string|null;original_storage_path:string|null;original_sha256:string|null;drive_original_file_id:string|null;metadata?:{source_sha256?:string}|null}
type Communication={id:string;channel:string;direction:string;subject:string|null;body:string;created_at:string}
type SignatureRequest={id:string;document_id:string;document_version_id:string;client_id:string;project_id:string|null;signer_name:string;signer_email:string;signer_side:'client'|'srccvde';signature_kind:'signature'|'acknowledgment';status:string;consent_text:string;requested_at:string;signed_at:string|null;legal_name:string|null}
type DocumentVersion={id:string;document_id:string;version_number:number;content_snapshot:string;content_sha256:string;state:string;created_at:string}
type Milestone={id:string;project_id:string;milestone_key:string;title:string;description:string|null;position:number;status:string;client_visible:boolean}

const leadStatuses=['new','contacted','discovery','proposal','contract','won','lost','archived']
const stages=['Inquiry','Discovery','Proposal','Contract','Kickoff','Build','Launch']
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const date=(s:string)=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(s))
const path=()=>window.location.pathname.replace(/\/+$/,'')||'/'

function Brand(){return <a className="brand" href="/" onClick={e=>{e.preventDefault();history.pushState({},'', '/');dispatchEvent(new PopStateEvent('popstate'))}} aria-label="SRCcvde workspace"><span>SRC</span>cvde<i/></a>}
function Avatar({name}:{name:string}){return <div className="avatar">{name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div>}
function Empty({children}:{children:string}){return <div className="empty">{children}</div>}
function StatusPill({value}:{value:string}){return <span className={'pill '+value}>{label(value)}</span>}

function Login(){
 const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const{error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setMessage(error.message)}
 async function reset(){if(!email){setMessage('Enter your email first.');return}setBusy(true);const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:'https://app.srccvde.com/set-password'});setBusy(false);setMessage(error?error.message:'Password reset email sent.')}
 return <main className="auth-page"><section className="auth-copy"><Brand/><p className="eyebrow">SRCcvde Workspace</p><h1>Your project has a home.</h1><p>One secure place for progress, documents, approvals, change requests and everything we build together.</p><div className="stage-preview">{stages.map((s,i)=><div key={s}><b>{String(i+1).padStart(2,'0')}</b><span>{s}</span></div>)}</div></section><section className="auth-panel"><form onSubmit={submit}><p className="eyebrow">Private access</p><h2>Welcome back.</h2><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><button className="text-button" type="button" onClick={reset} disabled={busy}>Forgot password?</button>{message&&<p className="form-message">{message}</p>}<p className="fine">Accounts are created by SRCcvde. Project applicants receive access when their workspace is ready.</p></form></section></main>
}

function SetPassword(){
 const[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 async function submit(e:FormEvent){e.preventDefault();if(password.length<8){setMessage('Use at least 8 characters.');return}if(password!==confirm){setMessage('Passwords do not match.');return}setBusy(true);const{error}=await supabase.auth.updateUser({password});setBusy(false);if(error){setMessage(error.message);return}history.replaceState({},'', '/');location.reload()}
 return <main className="auth-page"><section className="auth-copy"><Brand/><p className="eyebrow">SRCcvde Workspace</p><h1>Make this workspace yours.</h1><p>Create the password you'll use whenever you return to app.srccvde.com.</p></section><section className="auth-panel"><form onSubmit={submit}><p className="eyebrow">Account setup</p><h2>Set your password.</h2><label>New password<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/></label><label>Confirm password<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={8}/></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save password & continue'}</button>{message&&<p className="form-message">{message}</p>}</form></section></main>
}

const PUSH_PUBLIC_KEY='BL69KF1eYFXO1LSqLxw0Hp2gYCeJvobxGFN4cXC_h-Nx8hrnxTIadP6WUWfQVEPjmEgf1C-hEmFCCtJcNJHZugI'
function pushKeyBytes(value:string){const padding='='.repeat((4-value.length%4)%4);const raw=atob((value+padding).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)))}

function NotificationsPage(){
 const defaults={project_updates:true,documents:true,approvals:true,messages:true,billing:true,security:true,marketing:false}
 const[prefs,setPrefs]=useState<Record<string,boolean>>(defaults),[loadingPrefs,setLoadingPrefs]=useState(true),[saving,setSaving]=useState(''),[notice,setNotice]=useState(''),[permission,setPermission]=useState<NotificationPermission>(typeof Notification==='undefined'?'default':Notification.permission),[requesting,setRequesting]=useState(false),[subscribed,setSubscribed]=useState(false)
 const supported=typeof window!=='undefined'&&'Notification' in window&&'serviceWorker' in navigator&&'PushManager' in window
 const categories=[['project_updates','Project updates','Milestones, status changes, and project activity.'],['documents','Documents & signatures','Documents that need review, signature, or acknowledgment.'],['approvals','Approvals','Decisions and approvals waiting for you.'],['messages','Messages','New workspace messages and replies.'],['billing','Billing','Invoice and payment-status updates.'],['security','Security & account','Important account and security activity.'],['marketing','Product news & marketing','Optional SRCcvde product news. Off by default.']]
 useEffect(()=>{let alive=true;supabase.auth.getUser().then(async({data})=>{if(!data.user){if(alive)setLoadingPrefs(false);return}const{data:p,error}=await supabase.from('notification_preferences').select('project_updates,documents,approvals,messages,billing,security,marketing').eq('user_id',data.user.id).maybeSingle();if(alive){if(p)setPrefs({...defaults,...p});if(error)setNotice('Could not load saved notification preferences.');setLoadingPrefs(false)}if(supported&&Notification.permission==='granted'){try{const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();if(alive)setSubscribed(Boolean(sub))}catch{}}});return()=>{alive=false}},[])
 async function toggle(key:string){const next={...prefs,[key]:!prefs[key]};setPrefs(next);setSaving(key);setNotice('');const{data:{user}}=await supabase.auth.getUser();if(!user){setNotice('Please sign in again.');setSaving('');return}const{error}=await supabase.from('notification_preferences').upsert({user_id:user.id,...next,updated_at:new Date().toISOString()});if(error){setPrefs(prefs);setNotice('That preference could not be saved. Please try again.')}else setNotice('Preferences saved.');setSaving('')}
 async function sendTestNotification(){setRequesting(true);setNotice('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in again.');const{data,error}=await supabase.functions.invoke('send-push-notification',{body:{user_id:user.id,category:'security',title:'SRCcvde notifications are live',body:'Your test notification arrived. Push is working on this device.',url:'/notifications',tag:'push-test'}});if(error)throw error;setNotice(data?.sent>0?'Test notification sent. Check this device.':data?.skipped==='preference_disabled'?'Security notifications are disabled in your preferences.':'No active device subscription was available. Disable and re-enable notifications, then try again.')}catch(e){setNotice(e instanceof Error?e.message:'Could not send the test notification.')}finally{setRequesting(false)}}
 async function disableThisDevice(){if(!supported)return;setRequesting(true);setNotice('');try{const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();const{data:{user}}=await supabase.auth.getUser();if(sub&&user){await supabase.from('push_subscriptions').update({enabled:false,revoked_at:new Date().toISOString()}).eq('user_id',user.id).eq('endpoint',sub.endpoint);await sub.unsubscribe();await supabase.from('notification_consent_events').insert({user_id:user.id,action:'revoked',consent_text_version:'push-consent-2026-10-02-v1'})}setSubscribed(false);setNotice('Push notifications are disabled for this device.')}catch{setNotice('Could not disable this device. Please try again.')}finally{setRequesting(false)}}
 async function requestPermission(){if(!supported)return;setRequesting(true);setNotice('');try{const result=await Notification.requestPermission();setPermission(result);const{data:{user}}=await supabase.auth.getUser();if(user)await supabase.from('notification_consent_events').insert({user_id:user.id,action:result==='granted'?'granted':'denied',consent_text_version:'push-consent-2026-10-02-v1'});if(result==='granted'&&user){const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:pushKeyBytes(PUSH_PUBLIC_KEY)});const json=sub.toJSON();const{error:subError}=await supabase.from('push_subscriptions').upsert({user_id:user.id,endpoint:sub.endpoint,p256dh:json.keys?.p256dh||'',auth_key:json.keys?.auth||'',user_agent:navigator.userAgent,enabled:true,consented_at:new Date().toISOString(),revoked_at:null},{onConflict:'endpoint'});if(subError)throw subError;setSubscribed(true);setNotice('Notifications are enabled on this device.')}else setNotice(result==='denied'?'Notifications are blocked for this site. You can change that in your device or browser settings.':'Notification permission was not enabled.')}catch{setNotice('Could not request notification permission on this device.')}finally{setRequesting(false)}}
 const state=!supported?'Unsupported':permission==='granted'?'Allowed':permission==='denied'?'Blocked':'Not enabled'
 return <><header className="page-title"><p className="eyebrow">Device preferences</p><h1>Notifications</h1><p>Choose how SRCcvde keeps you updated on this device.</p></header><section className="panel"><div className="section-head"><div><p className="eyebrow">Permission</p><h2>Push notifications</h2></div><span className="status-pill">{state}</span></div><p className="muted">Enable SRCcvde notifications on this device for project, document, approval, billing, message, and security updates. Notifications may appear on your lock screen depending on your device settings. You can change categories or disable notifications later.</p>{permission==='default'&&supported&&<button className="primary" disabled={requesting} onClick={requestPermission}>{requesting?'Requesting…':'Enable notifications'}</button>}{permission==='granted'&&<><p className="muted">{subscribed?'This device is subscribed and ready to receive SRCcvde push notifications.':'Permission is allowed. If this device has not finished subscribing, re-enable notifications to complete setup.'}</p><div className="detail-actions"><button className="primary" disabled={requesting} onClick={subscribed?sendTestNotification:requestPermission}>{requesting?'Working…':subscribed?'Send test notification':'Finish device setup'}</button>{subscribed&&<button className="secondary" disabled={requesting} onClick={disableThisDevice}>{requesting?'Updating…':'Disable on this device'}</button>}</div></>}{permission==='denied'&&<p className="muted">Your browser or device has blocked notifications. SRCcvde cannot override that choice.</p>}{!supported&&<p className="muted">Push notifications are not available in this browser or app mode.</p>}</section><section className="panel"><div className="section-head"><div><p className="eyebrow">Preferences</p><h2>What can notify you</h2></div></div><div className="notification-preferences">{categories.map(([key,name,copy])=><label className="preference-row" key={key}><span><b>{name}</b><small>{copy}</small></span><input type="checkbox" checked={Boolean(prefs[key])} disabled={loadingPrefs||saving===key} onChange={()=>toggle(key)} aria-label={name}/></label>)}</div>{notice&&<p className="muted">{notice}</p>}<p className="muted">Marketing remains separate from operational notifications and is off by default.</p></section></>
}

function Sidebar({role,current,navigate,onSignOut,mobileOpen=false,onNavigate}:{role:Role;current:string;navigate:(p:string)=>void;onSignOut:()=>void;mobileOpen?:boolean;onNavigate?:()=>void}){
 const admin=role!=='client'
 const items=admin?[['Overview','/'],['Leads','/leads'],['Clients','/clients'],['Projects','/projects'],['Documents','/documents'],['Activity','/activity'],['Notifications','/notifications']]:[['Overview','/'],['Project','/project'],['Documents','/documents'],['Activity','/activity'],['Notifications','/notifications']]
 return <aside className={'sidebar'+(mobileOpen?' mobile-open':'')}><Brand/><nav>{items.map(([name,p])=><button className={(p==='/'?current==='/':current.startsWith(p))?'active':''} onClick={()=>{navigate(p);onNavigate?.()}} key={p}><span>{name[0]}</span>{name}</button>)}</nav><div className="sidebar-bottom"><small>{admin?'SRCcvde team':'Client workspace'}</small><button onClick={onSignOut}>Sign out</button></div></aside>
}

function AdminOverview({profile,navigate}:{profile:Profile|null;navigate:(p:string)=>void}){
 const[inquiries,setInquiries]=useState<Inquiry[]>([]),[clients,setClients]=useState(0),[projects,setProjects]=useState(0),[loading,setLoading]=useState(true)
 useEffect(()=>{Promise.all([
  supabase.from('project_inquiries').select('*').order('created_at',{ascending:false}).limit(6),
  supabase.from('clients').select('*',{count:'exact',head:true}).in('status',['onboarding','active']),
  supabase.from('projects').select('*',{count:'exact',head:true}).in('status',['planning','active','launching'])
 ]).then(([i,c,p])=>{setInquiries((i.data||[]) as Inquiry[]);setClients(c.count||0);setProjects(p.count||0);setLoading(false)})},[])
 const first=profile?.full_name?' '+profile.full_name.split(' ')[0]:''
 return <><header className="topbar"><div><p className="eyebrow">Command center</p><h1>Good to see you{first}.</h1></div><span className="live-dot">Live workspace</span></header>
 <section className="metric-grid"><article><small>New inquiries</small><strong>{loading?'—':inquiries.filter(x=>x.status==='new').length}</strong><span>recent queue</span></article><article><small>Active clients</small><strong>{loading?'—':clients}</strong><span>onboarding + active</span></article><article><small>Active projects</small><strong>{loading?'—':projects}</strong><span>current workspaces</span></article><article><small>Needs attention</small><strong>{loading?'—':inquiries.filter(x=>['new','contract'].includes(x.status)).length}</strong><span>new + contract stage</span></article></section>
 <section className="panel"><div className="section-head"><div><p className="eyebrow">CRM</p><h2>Latest inquiries</h2></div><button className="ghost" onClick={()=>navigate('/leads')}>View pipeline →</button></div>{loading?<p className="muted">Loading inquiries…</p>:inquiries.length===0?<Empty>No inquiries yet.</Empty>:<div className="lead-list">{inquiries.map(x=><button className="lead-row" key={x.id} onClick={()=>navigate('/leads/'+x.id)}><Avatar name={x.name}/><div><b>{x.name}</b><small>{x.company||x.email}</small></div><span>{x.project_type}</span><StatusPill value={x.status}/></button>)}</div>}</section></>
}

function LeadsPage({navigate}:{navigate:(p:string)=>void}){
 const[leads,setLeads]=useState<Inquiry[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{supabase.from('project_inquiries').select('*').order('created_at',{ascending:false}).then(({data})=>{setLeads((data||[]) as Inquiry[]);setLoading(false)})},[])
 return <><PageTitle eyebrow="CRM" title="Leads" copy="Every project inquiry, from first hello to signed client."/><div className="pipeline">{leadStatuses.slice(0,5).map(status=><section className="pipeline-col" key={status}><div className="pipeline-head"><b>{label(status)}</b><span>{leads.filter(x=>x.status===status).length}</span></div>{leads.filter(x=>x.status===status).map(x=><button className="lead-card" key={x.id} onClick={()=>navigate('/leads/'+x.id)}><div><Avatar name={x.name}/><span><b>{x.name}</b><small>{x.company||x.project_type}</small></span></div><p>{x.details}</p><footer><small>{date(x.created_at)}</small><small>{x.budget_range}</small></footer></button>)}{!loading&&!leads.some(x=>x.status===status)&&<div className="pipeline-empty">Nothing here</div>}</section>)}</div>
 <section className="panel"><div className="section-head"><h2>Closed & archived</h2><span className="status">{leads.filter(x=>['won','lost','archived'].includes(x.status)).length}</span></div><div className="compact-list">{leads.filter(x=>['won','lost','archived'].includes(x.status)).map(x=><button key={x.id} onClick={()=>navigate('/leads/'+x.id)}><span>{x.name}</span><StatusPill value={x.status}/></button>)}</div></section></>
}

function LeadDetail({id,navigate}:{id:string;navigate:(p:string)=>void}){
 const[lead,setLead]=useState<Inquiry|null>(null),[notes,setNotes]=useState<Note[]>([]),[activity,setActivity]=useState<Activity[]>([]),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{const[l,n,a]=await Promise.all([supabase.from('project_inquiries').select('*').eq('id',id).single(),supabase.from('lead_notes').select('id,body,created_at').eq('inquiry_id',id).order('created_at',{ascending:false}),supabase.from('crm_activity').select('*').eq('entity_type','lead').eq('entity_id',id).order('created_at',{ascending:false})]);setLead(l.data as Inquiry);setNotes((n.data||[]) as Note[]);setActivity((a.data||[]) as Activity[])}
 useEffect(()=>{load()},[id])
 async function changeStatus(status:string){if(!lead)return;setBusy(true);const{error}=await supabase.from('project_inquiries').update({status}).eq('id',id);setBusy(false);if(error)setMessage(error.message);else load()}
 async function addNote(e:FormEvent){e.preventDefault();if(!note.trim())return;setBusy(true);const{error}=await supabase.from('lead_notes').insert({inquiry_id:id,body:note.trim()});setBusy(false);if(error)setMessage(error.message);else{setNote('');load()}}
 async function inviteApplicant(){setBusy(true);setMessage('');const{data,error}=await supabase.functions.invoke('invite-applicant',{body:{inquiry_id:id}});setBusy(false);setMessage(error?error.message:(data?.invitation_sent?'Applicant portal invitation sent.':'Applicant account linked.'));if(!error)load()}
 async function convert(){if(!lead)return;setBusy(true);setMessage('');const{data,error}=await supabase.rpc('convert_lead_to_client',{p_inquiry_id:id});setBusy(false);if(error)setMessage(error.message);else navigate('/clients/'+data)}
 if(!lead)return <p className="muted">Loading lead…</p>
 return <><button className="back" onClick={()=>navigate('/leads')}>← Leads</button><header className="detail-head"><div className="identity"><Avatar name={lead.name}/><div><p className="eyebrow">Lead</p><h1>{lead.name}</h1><p>{lead.company||lead.email}</p></div></div><div className="detail-actions"><select value={lead.status} disabled={busy} onChange={e=>changeStatus(e.target.value)}>{leadStatuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><button className="ghost" disabled={busy} onClick={inviteApplicant}>Invite to applicant portal</button>{lead.status!=='won'&&<button className="primary inline" disabled={busy} onClick={convert}>Convert to client</button>}</div></header>
 {message&&<p className="success-message">{message}</p>}<div className="detail-grid"><section className="panel flush"><p className="eyebrow">Project brief</p><div className="facts"><Fact k="Email" v={lead.email}/><Fact k="Project type" v={lead.project_type}/><Fact k="Budget" v={lead.budget_range}/><Fact k="Timeline" v={lead.timeline}/><Fact k="Involvement" v={lead.involvement}/><Fact k="Received" v={date(lead.created_at)}/></div><div className="brief"><small>What they want to build</small><p>{lead.details}</p></div></section>
 <aside><section className="panel flush"><p className="eyebrow">Internal notes</p><form className="note-form" onSubmit={addNote}><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a private note…" maxLength={5000}/><button className="primary" disabled={busy||!note.trim()}>Add note</button></form>{notes.map(n=><div className="note" key={n.id}><p>{n.body}</p><small>{date(n.created_at)}</small></div>)}</section><ActivityFeed rows={activity}/></aside></div></>
}

function ClientsPage({navigate}:{navigate:(p:string)=>void}){
 const[clients,setClients]=useState<Client[]>([])
 useEffect(()=>{supabase.from('clients').select('*').order('created_at',{ascending:false}).then(({data})=>setClients((data||[]) as Client[]))},[])
 return <><PageTitle eyebrow="Relationships" title="Clients" copy="Accepted clients and the workspaces attached to them."/><section className="panel"><div className="client-list">{clients.map(c=><button className="client-row" key={c.id} onClick={()=>navigate('/clients/'+c.id)}><Avatar name={c.name}/><div><b>{c.name}</b><small>{c.primary_contact_name} · {c.primary_email}</small></div><StatusPill value={c.status}/><span>Open →</span></button>)}{clients.length===0&&<Empty>No clients yet. Convert a lead when you're ready.</Empty>}</div></section></>
}

function ClientDetail({id,navigate}:{id:string;navigate:(p:string)=>void}){
 const[client,setClient]=useState<(Client&{portal_unlocked?:boolean})|null>(null),[projects,setProjects]=useState<Project[]>([]),[docs,setDocs]=useState<DocumentRow[]>([]),[comms,setComms]=useState<Communication[]>([]),[activity,setActivity]=useState<Activity[]>([]),[requests,setRequests]=useState<SignatureRequest[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[downloadUrl,setDownloadUrl]=useState('')
 const[docName,setDocName]=useState(''),[docCategory,setDocCategory]=useState('agreement'),[docKind,setDocKind]=useState('signature'),[docContent,setDocContent]=useState('')
 const load=async()=>{const[c,p,d,m,a,s]=await Promise.all([supabase.from('clients').select('*').eq('id',id).single(),supabase.from('projects').select('*').eq('client_id',id).order('created_at'),supabase.from('client_documents').select('*').eq('client_id',id).order('created_at',{ascending:false}),supabase.from('client_communications').select('*').eq('client_id',id).order('created_at',{ascending:false}),supabase.from('crm_activity').select('*').eq('entity_type','client').eq('entity_id',id).order('created_at',{ascending:false}),supabase.from('signature_requests').select('*').eq('client_id',id).order('requested_at',{ascending:false})]);setClient(c.data as Client&{portal_unlocked?:boolean});setProjects((p.data||[]) as Project[]);setDocs((d.data||[]) as DocumentRow[]);setComms((m.data||[]) as Communication[]);setActivity((a.data||[]) as Activity[]);setRequests((s.data||[]) as SignatureRequest[])}
 useEffect(()=>{load()},[id])
 async function invite(){setBusy(true);setMessage('');const{data,error}=await supabase.functions.invoke('invite-client',{body:{client_id:id}});setBusy(false);setMessage(error?error.message:(data?.invitation_sent?'Portal invitation sent.':'Client account linked.'));if(!error)load()}
 async function createDocument(e:FormEvent){e.preventDefault();const project=projects[0];if(!project)return setMessage('This client needs a project first.');setBusy(true);setMessage('');const{error}=await supabase.rpc('create_signable_document',{p_client_id:id,p_project_id:project.id,p_name:docName,p_category:docCategory,p_content:docContent,p_signature_kind:docKind});setBusy(false);if(error)setMessage(error.message);else{setDocName('');setDocContent('');setMessage('Document sent to the client workspace.');load()}}
 async function countersign(documentId:string){const legalName=prompt('Type your legal name to countersign this exact document version.');if(!legalName)return;setBusy(true);setMessage('');setDownloadUrl('');const{error}=await supabase.rpc('countersign_document',{p_document_id:documentId,p_legal_name:legalName});if(error){setBusy(false);setMessage(error.message);return}const{data,error:finalError}=await supabase.functions.invoke('finalize-executed-document',{body:{document_id:documentId}});setBusy(false);if(finalError)setMessage('Fully executed. PDF archive needs attention: '+finalError.message);else{setMessage(data?.drive?.status==='synced'?'Fully executed and archived to Google Drive.':'Fully executed. Secure PDF generated; Google Drive sync is waiting for its one-time connection.');setDownloadUrl(data?.download_url||'')}load()}
 async function retryArchive(documentId:string){setBusy(true);setMessage('');setDownloadUrl('');const{data,error}=await supabase.functions.invoke('finalize-executed-document',{body:{document_id:documentId}});setBusy(false);if(error)setMessage('PDF archive still needs attention: '+error.message);else{setMessage(data?.drive?.status==='synced'?'Executed PDF generated and archived to Google Drive.':'Executed PDF generated. Google Drive archive status: '+(data?.drive?.status||data?.artifact?.drive_sync_status||'pending')+'.');setDownloadUrl(data?.download_url||'')}load()}
 if(!client)return <p className="muted">Loading client…</p>
 const requestFor=(documentId:string)=>requests.find(r=>r.document_id===documentId&&r.signer_side==='client')
 return <><button className="back" onClick={()=>navigate('/clients')}>← Clients</button><header className="detail-head"><div className="identity"><Avatar name={client.name}/><div><p className="eyebrow">Client record</p><h1>{client.name}</h1><p>{client.primary_contact_name} · {client.primary_email}</p></div></div><div className="detail-actions"><StatusPill value={client.portal_unlocked?'active':'onboarding'}/><button className="primary inline" disabled={busy} onClick={invite}>{busy?'Working…':'Invite / link portal'}</button></div></header>{message&&<p className="success-message">{message}{downloadUrl&&<> · <a href={downloadUrl} target="_blank" rel="noreferrer">Download executed PDF</a></>}</p>}
 <section className="record-grid"><RecordCard title="Projects" count={projects.length} detail={projects[0]?projects[0].name:'No projects'}/><RecordCard title="Documents" count={docs.length} detail={client.drive_folder_id?'Drive connected':'Drive archive pending'}/><RecordCard title="Communications" count={comms.length} detail="Client history"/><RecordCard title="Portal" count={client.portal_unlocked?1:0} detail={client.portal_unlocked?'Full workspace unlocked':'Pre-project experience'}/></section>
 <div className="detail-grid"><section><section className="panel flush"><div className="section-head"><div><p className="eyebrow">Projects</p><h2>Workspace</h2></div></div>{projects.map(p=><div className="project-row" key={p.id}><div><b>{p.name}</b><small>{label(p.phase)} · {p.project_type}</small></div><div className="progress"><i style={{width:p.progress+'%'}}/></div><StatusPill value={p.status}/></div>)}</section>
 <section className="panel"><div className="section-head"><div><p className="eyebrow">Documents</p><h2>Signing room</h2></div><span className="status">{docs.length}</span></div>{docs.length?docs.map(d=>{const req=requestFor(d.id);return <div className="doc-row signable-row" key={d.id}><div><b>{d.name}</b><small>{label(d.category)} · {req?label(req.status):label(d.state)}</small></div>{req?.status==='signed'&&d.state!=='final'&&d.signature_kind!=='acknowledgment'?<button className="ghost" disabled={busy} onClick={()=>countersign(d.id)}>Countersign & finalize</button>:d.state==='final'&&!d.executed_artifact_id?<button className="ghost" disabled={busy} onClick={()=>retryArchive(d.id)}>{busy?'Working…':'Generate & archive PDF'}</button>:<StatusPill value={d.state}/>}</div>}):<Empty>No documents yet.</Empty>}</section>
 <section className="panel"><p className="eyebrow">Create document</p><h2>Send an exact version for review</h2><form className="document-form" onSubmit={createDocument}><label>Document name<input value={docName} onChange={e=>setDocName(e.target.value)} placeholder="Project Agreement" required/></label><div className="form-split"><label>Category<select value={docCategory} onChange={e=>setDocCategory(e.target.value)}><option value="agreement">Agreement</option><option value="proposal">Proposal</option><option value="scope">Scope</option><option value="approval">Approval</option></select></label><label>Action<select value={docKind} onChange={e=>setDocKind(e.target.value)}><option value="signature">Signature required</option><option value="acknowledgment">Acknowledgment required</option></select></label></div><label>Exact document content<textarea className="document-editor" value={docContent} onChange={e=>setDocContent(e.target.value)} placeholder="Paste or compose the exact version the client will review…" required minLength={20}/></label><button className="primary" disabled={busy}>Send to client workspace</button></form></section></section><aside><ActivityFeed rows={activity}/></aside></div></>
}

function ProjectsPage(){const[rows,setRows]=useState<Project[]>([]);useEffect(()=>{supabase.from('projects').select('*').order('created_at',{ascending:false}).then(({data})=>setRows((data||[]) as Project[]))},[]);return <><PageTitle eyebrow="Delivery" title="Projects" copy="Every active build, its phase and current progress."/><section className="panel">{rows.map(p=><div className="project-row" key={p.id}><div><b>{p.name}</b><small>{p.project_type||'Custom project'} · {label(p.phase)}</small></div><div className="progress"><i style={{width:p.progress+'%'}}/></div><strong>{p.progress}%</strong><StatusPill value={p.status}/></div>)}{!rows.length&&<Empty>No projects yet.</Empty>}</section></>}
function DocumentsPage(){
 const[rows,setRows]=useState<DocumentRow[]>([]),[artifacts,setArtifacts]=useState<ExecutedArtifact[]>([]),[integration,setIntegration]=useState<any>(null),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[downloadUrl,setDownloadUrl]=useState(''),[originalDownloadUrl,setOriginalDownloadUrl]=useState(''),[clientId,setClientId]=useState(''),[clientSecret,setClientSecret]=useState('')
 const load=async()=>{const[d,a,g]=await Promise.all([supabase.from('client_documents').select('*').order('created_at',{ascending:false}),supabase.from('executed_document_artifacts').select('*').order('generated_at',{ascending:false}),supabase.from('app_integrations').select('*').eq('provider','google_drive').maybeSingle()]);setRows((d.data||[]) as DocumentRow[]);setArtifacts((a.data||[]) as ExecutedArtifact[]);setIntegration(g.data||null)}
 useEffect(()=>{load();const p=new URLSearchParams(location.search);if(p.get('drive')==='connected'){setMessage('Google Drive connected. Executed documents can now archive automatically.');history.replaceState({},'',location.pathname)}else if(p.get('drive')==='error'){setMessage('Google Drive connection failed: '+label(p.get('reason')||'unknown error'));history.replaceState({},'',location.pathname)}},[])
 async function saveGoogleCredentials(e:FormEvent){e.preventDefault();setBusy('google-config');setMessage('');const{error}=await supabase.rpc('configure_google_drive_oauth',{p_client_id:clientId.trim(),p_client_secret:clientSecret.trim()});setBusy('');setClientSecret('');if(error)setMessage(error.message);else{setMessage('OAuth credentials stored securely. Now connect the SRCcvde Drive account.');load()}}
 async function connectGoogle(){setBusy('google-connect');setMessage('');const{data,error}=await supabase.rpc('begin_google_drive_oauth');setBusy('');const c=data?.[0];if(error||!c?.client_id||!c?.state){setMessage(error?.message||'Could not start Google authorization.');return}const p=new URLSearchParams({client_id:c.client_id,redirect_uri:c.redirect_uri,response_type:'code',scope:c.scope,access_type:'offline',prompt:'consent',state:c.state,trigger_onepick:'true',allow_folder_selection:'true',file_ids:'1j23qs5KZowr6BuVbbRnQdQvGN6mHhsG2'});window.location.assign('https://accounts.google.com/o/oauth2/v2/auth?'+p.toString())}
 async function archive(documentId:string){setBusy(documentId);setMessage('');setDownloadUrl('');setOriginalDownloadUrl('');const{data,error}=await supabase.functions.invoke('finalize-executed-document',{body:{document_id:documentId}});setBusy('');if(error){let detail=error.message;try{const response=(error as any).context as Response|undefined;if(response){const body=await response.clone().json();detail=body?.detail||body?.error||detail}}catch{}setMessage(detail)}else{setDownloadUrl(data?.download_url||'');setOriginalDownloadUrl(data?.original_download_url||'');setMessage(data?.drive?.status==='synced'?'Executed PDF is safely archived in Google Drive.':data?.artifact?.drive_sync_status==='synced'?'Executed PDF is safely archived in Google Drive.':'Executed PDF is in the secure vault. Google Drive sync needs attention.');load()}}
 const artifactFor=(id:string)=>artifacts.find(a=>a.document_id===id)
 return <><PageTitle eyebrow="Vault" title="Documents" copy="Immutable executed PDFs, signature certificates and the Google Drive archive index."/>
 {message&&<p className="success-message">{message}{originalDownloadUrl&&<> · <a href={originalDownloadUrl} target="_blank" rel="noreferrer">Original</a></>}{downloadUrl&&<> · <a href={downloadUrl} target="_blank" rel="noreferrer">Executed</a></>}</p>}
 <section className="panel drive-connect"><div className="section-head"><div><p className="eyebrow">Archive integration</p><h2>Google Drive</h2></div><span className={'sync-state '+(integration?.status==='connected'?'synced':'')}>{integration?.status==='connected'?'Connected':integration?.status==='configured'?'Ready to connect':'Not connected'}</span></div>
 {integration?.status==='connected'?<div className="connected-drive"><div><b>{integration.root_folder_name||'03 — Clients'}</b><small>Executed PDFs archive automatically into each client's folder.</small></div><button className="ghost" onClick={connectGoogle} disabled={busy==='google-connect'}>Reconnect</button></div>:integration?.status==='configured'?<><p className="muted">Credentials are encrypted in Supabase Vault. Authorize SRCcvde to the client archive folder to finish.</p><button className="primary inline" onClick={connectGoogle} disabled={busy==='google-connect'}>{busy==='google-connect'?'Opening Google…':'Connect SRCcvde Drive'}</button></>:<form className="google-credential-form" onSubmit={saveGoogleCredentials}><p className="muted">Paste the OAuth credential here instead of chat. The client secret is sent directly to Supabase over HTTPS and stored encrypted in Vault; it is never committed to GitHub.</p><label>Google OAuth Client ID<input value={clientId} onChange={e=>setClientId(e.target.value)} autoComplete="off" required placeholder="…apps.googleusercontent.com"/></label><label>Google OAuth Client Secret<input type="password" value={clientSecret} onChange={e=>setClientSecret(e.target.value)} autoComplete="new-password" required placeholder="GOCSPX-…"/></label><button className="primary inline" disabled={busy==='google-config'}>{busy==='google-config'?'Securing…':'Save securely'}</button></form>}</section>
 <section className="panel">{rows.map(d=>{const a=artifactFor(d.id);return <div className="doc-row vault-row" key={d.id}><div><b>{d.name}</b><small>{label(d.category)}{a?.metadata?.source_sha256?' · Source '+a.metadata.source_sha256.slice(0,12)+'…':''}{a?' · Executed '+a.final_sha256.slice(0,12)+'…':''}</small></div><div className="vault-actions">{a&&<span className={'sync-state '+a.drive_sync_status}>{a.drive_sync_status==='synced'&&a.drive_original_file_id?'Original + executed archived':a.drive_sync_status==='synced'?'Executed archived':a.drive_sync_status==='failed'?'Drive retry needed':'Secure vault'}</span>}{d.state==='final'?<button className="ghost" disabled={busy===d.id} onClick={()=>archive(d.id)}>{busy===d.id?'Preparing…':a?'Open document archive':'Generate document archive'}</button>:<StatusPill value={d.state}/>}</div></div>})}{!rows.length&&<Empty>No documents indexed yet.</Empty>}</section></>}
function ActivityPage(){const[rows,setRows]=useState<Activity[]>([]);useEffect(()=>{supabase.from('crm_activity').select('*').order('created_at',{ascending:false}).limit(100).then(({data})=>setRows((data||[]) as Activity[]))},[]);return <><PageTitle eyebrow="Audit trail" title="Activity" copy="A timestamped history of meaningful CRM and client actions."/><ActivityFeed rows={rows}/></>}

function ActivityFeed({rows}:{rows:Activity[]}){return <section className="panel activity-panel"><p className="eyebrow">Activity</p>{rows.length?rows.map(a=><div className="activity-item" key={a.id}><i/><div><b>{a.summary}</b><small>{date(a.created_at)} · {label(a.action)}</small></div></div>):<Empty>No activity yet.</Empty>}</section>}
function PageTitle({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <header className="page-title"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></header>}
function Fact({k,v}:{k:string;v:string}){return <div><small>{k}</small><b>{v}</b></div>}
function RecordCard({title,count,detail}:{title:string;count:number;detail:string}){return <article><small>{title}</small><strong>{count}</strong><span>{detail}</span></article>}

function ApplicantTimeline({inquiry}:{inquiry:Inquiry}){
 const flow=['application','discovery','proposal','contract','kickoff']
 const current=inquiry.status==='discovery'?1:inquiry.status==='proposal'?2:inquiry.status==='contract'?3:inquiry.status==='won'?4:0
 return <section className="timeline-card"><div className="section-head"><div><p className="eyebrow">Your journey</p><h2>{current===0?'Application received':current===1?'Discovery':current===2?'Proposal':current===3?'Contract':'Project kickoff'}</h2></div><span className="status">{label(inquiry.status)}</span></div><div className="timeline">{flow.map((s,i)=><div className={i<current?'done':i===current?'current':''} key={s}><i/><b>{label(s)}</b><small>{i<current?'Complete':i===current?'Current step':'Upcoming'}</small></div>)}</div></section>
}

function SignatureCard({request,navigate}:{request:SignatureRequest;navigate:(p:string)=>void}){return <button className="signature-card" onClick={()=>navigate('/documents/'+request.id)}><div><span className="signature-icon">✦</span><div><b>{request.signature_kind==='signature'?'Signature required':'Acknowledgment required'}</b><small>{request.signer_name} · requested {date(request.requested_at)}</small></div></div><span>Review →</span></button>}

function SignDocumentPage({requestId,navigate}:{requestId:string;navigate:(p:string)=>void}){
 const[request,setRequest]=useState<SignatureRequest|null>(null),[version,setVersion]=useState<DocumentVersion|null>(null),[doc,setDoc]=useState<DocumentRow|null>(null),[legalName,setLegalName]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{(async()=>{const{data:r}=await supabase.from('signature_requests').select('*').eq('id',requestId).single();if(!r)return;setRequest(r as SignatureRequest);const[v,d]=await Promise.all([supabase.from('document_versions').select('*').eq('id',r.document_version_id).single(),supabase.from('client_documents').select('*').eq('id',r.document_id).single()]);setVersion(v.data as DocumentVersion);setDoc(d.data as DocumentRow);await supabase.rpc('mark_signature_viewed',{p_request_id:requestId})})()},[requestId])
 async function sign(){if(!request)return;setBusy(true);setMessage('');const{error}=await supabase.rpc('sign_document',{p_request_id:requestId,p_legal_name:legalName,p_signature_value:legalName,p_consent:consent});if(error){setBusy(false);setMessage(error.message);return}let note=request.signature_kind==='signature'?'Signed successfully. SRCcvde has been notified.':'Acknowledgment recorded.';if(request.signature_kind==='acknowledgment'){const{data,error:finalError}=await supabase.functions.invoke('finalize-executed-document',{body:{document_id:request.document_id}});if(!finalError&&data?.download_url)note+=' Your executed PDF is ready below.'}setBusy(false);setMessage(note);setRequest({...request,status:'signed',legal_name:legalName,signed_at:new Date().toISOString()})}
 if(!request||!version||!doc)return <p className="muted">Opening secure document…</p>
 return <><button className="back" onClick={()=>navigate('/')}>← Workspace</button><header className="page-title"><p className="eyebrow">Secure document</p><h1>{doc.name}</h1><p>Version {version.version_number} · SHA-256 {version.content_sha256.slice(0,12)}…</p></header><div className="signing-layout"><article className="document-paper"><div className="document-sheet-head"><Brand/><span>Secure review copy</span></div><div className="document-meta"><span>Exact document version · v{version.version_number}</span><StatusPill value={request.status}/></div><div className="document-rule"/><pre>{version.content_snapshot}</pre><footer><span>Document fingerprint</span><code>{version.content_sha256}</code></footer></article><aside className="panel signing-panel"><p className="eyebrow">{request.signature_kind==='signature'?'Electronic signature':'Acknowledgment'}</p>{request.status==='signed'?<><h2>Completed.</h2><p className="muted">Recorded as {request.legal_name}{request.signed_at?' on '+date(request.signed_at):''}.</p></>:<><p className="consent-copy">{request.consent_text}</p><label>Legal name<input value={legalName} onChange={e=>setLegalName(e.target.value)} placeholder={request.signer_name}/></label><label className="check-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to the electronic signing statement above.</span></label><button className="primary" disabled={busy||!consent||legalName.trim().length<2} onClick={sign}>{busy?'Recording…':request.signature_kind==='signature'?'Sign & Accept':'Reviewed & Acknowledged'}</button></>}{message&&<p className="success-message">{message}</p>}<p className="fine">Your action is recorded against this exact immutable document version and its cryptographic fingerprint.</p></aside></div></>
}

function ClientDashboard({profile,navigate}:{profile:Profile|null;navigate:(p:string)=>void}){
 const[inquiry,setInquiry]=useState<Inquiry|null>(null),[client,setClient]=useState<(Client&{portal_unlocked?:boolean})|null>(null),[project,setProject]=useState<Project|null>(null),[milestones,setMilestones]=useState<Milestone[]>([]),[requests,setRequests]=useState<SignatureRequest[]>([]),[docs,setDocs]=useState<DocumentRow[]>([])
 useEffect(()=>{(async()=>{const[{data:ims},{data:cms}]=await Promise.all([supabase.from('inquiry_memberships').select('inquiry_id').limit(1),supabase.from('client_memberships').select('client_id').limit(1)]);const inquiryId=ims?.[0]?.inquiry_id,clientId=cms?.[0]?.client_id;if(inquiryId){const{data}=await supabase.from('project_inquiries').select('*').eq('id',inquiryId).single();setInquiry(data as Inquiry)}if(!clientId)return;const[c,p,d,s]=await Promise.all([supabase.from('clients').select('*').eq('id',clientId).single(),supabase.from('projects').select('*').eq('client_id',clientId).order('created_at').limit(1),supabase.from('client_documents').select('*').eq('client_id',clientId).eq('client_visible',true).order('created_at',{ascending:false}),supabase.from('signature_requests').select('*').eq('client_id',clientId).eq('signer_side','client').order('requested_at',{ascending:false})]);setClient(c.data as Client&{portal_unlocked?:boolean});const proj=(p.data?.[0]||null) as Project|null;setProject(proj);setDocs((d.data||[]) as DocumentRow[]);setRequests((s.data||[]) as SignatureRequest[]);if(proj){const{data:ms}=await supabase.from('project_milestones').select('*').eq('project_id',proj.id).eq('client_visible',true).order('position');setMilestones((ms||[]) as Milestone[])}})()},[])
 const first=profile?.full_name?' '+profile.full_name.split(' ')[0]:''
 const pending=requests.filter(r=>r.status==='pending')
 return <><header className="topbar"><div><p className="eyebrow">{client?.portal_unlocked?'Client workspace':'Project journey'}</p><h1>Welcome{first}.</h1></div><span className="live-dot">Secure workspace</span></header>
 {pending.length>0&&<section className="attention"><div><p className="eyebrow">Action required</p><h2>{pending.length===1?'A document is ready for you.':pending.length+' documents are ready for you.'}</h2></div>{pending.map(r=><SignatureCard key={r.id} request={r} navigate={navigate}/>)}</section>}
 {!client&&inquiry&&<ApplicantTimeline inquiry={inquiry}/>}
 {client&&!client.portal_unlocked&&<><section className="timeline-card"><div className="section-head"><div><p className="eyebrow">Pre-project workspace</p><h2>{project?.phase?label(project.phase):'Contract'}</h2></div><span className="status">Workspace unlocks after execution</span></div><div className="timeline">{(milestones.length?milestones:[{milestone_key:'application',title:'Application',status:'completed'},{milestone_key:'discovery',title:'Discovery',status:'completed'},{milestone_key:'proposal',title:'Proposal',status:'completed'},{milestone_key:'contract',title:'Contract',status:'current'},{milestone_key:'kickoff',title:'Kickoff',status:'upcoming'}] as Milestone[]).map(m=><div className={m.status==='completed'?'done':m.status==='current'?'current':''} key={m.milestone_key}><i/><b>{m.title}</b><small>{m.status==='completed'?'Complete':m.status==='current'?'Current step':'Upcoming'}</small></div>)}</div></section><section className="two-col"><article className="panel"><p className="eyebrow">Documents</p><h2>{docs.length} shared</h2><p className="muted">Proposals, scope and agreements stay attached to your project journey.</p></article><article className="panel"><p className="eyebrow">What happens next</p><h2>One account. No restart.</h2><p className="muted">Once the agreement is fully executed, this same workspace opens into your project dashboard.</p></article></section></>}
 {client?.portal_unlocked&&project&&<><section className="timeline-card"><div className="section-head"><div><p className="eyebrow">Current project</p><h2>{project.name}</h2></div><StatusPill value={project.status}/></div><div className="client-progress"><div><span>{label(project.phase)}</span><strong>{project.progress}%</strong></div><div className="progress"><i style={{width:project.progress+'%'}}/></div></div></section><section className="two-col"><article className="panel"><p className="eyebrow">Current phase</p><h2>{label(project.phase)}</h2><p className="muted">Milestones, approvals and deliverables will stay organized here as the project moves forward.</p></article><article className="panel"><p className="eyebrow">Documents</p><h2>{docs.length} available</h2><p className="muted">Agreements, scope and deliverables live with your project.</p></article></section></>}
 {!inquiry&&!client&&<Empty>Your workspace is being prepared.</Empty>}</>
}

function ClientDocumentsPage({navigate}:{navigate:(p:string)=>void}){
 const[requests,setRequests]=useState<SignatureRequest[]>([])
 useEffect(()=>{supabase.from('signature_requests').select('*').eq('signer_side','client').order('requested_at',{ascending:false}).then(({data})=>setRequests((data||[]) as SignatureRequest[]))},[])
 return <><PageTitle eyebrow="Documents" title="Review & sign" copy="Every action is tied to the exact document version you reviewed."/><section className="panel">{requests.length?requests.map(r=><SignatureCard key={r.id} request={r} navigate={navigate}/>):<Empty>No documents need your attention right now.</Empty>}</section></>
}

function ClientRouter({route,profile,navigate}:{route:string;profile:Profile|null;navigate:(p:string)=>void}){
 const sign=route.match(/^\/documents\/([0-9a-f-]+)$/i)
 if(sign)return <SignDocumentPage requestId={sign[1]} navigate={navigate}/>
 if(route==='/documents')return <ClientDocumentsPage navigate={navigate}/>
 if(route==='/notifications')return <NotificationsPage/>
 return <ClientDashboard profile={profile} navigate={navigate}/>
}

function PendingAccess({email}:{email?:string}){return <main className="pending"><Brand/><p className="eyebrow">Workspace access</p><h1>You're signed in.</h1><p>{email} does not have an active SRCcvde workspace membership yet.</p><button className="primary" onClick={()=>supabase.auth.signOut()}>Sign out</button></main>}

function AdminRouter({route,profile,navigate}:{route:string;profile:Profile|null;navigate:(p:string)=>void}){
 const lead=route.match(/^\/leads\/([0-9a-f-]+)$/i),client=route.match(/^\/clients\/([0-9a-f-]+)$/i)
 if(lead)return <LeadDetail id={lead[1]} navigate={navigate}/>
 if(client)return <ClientDetail id={client[1]} navigate={navigate}/>
 if(route==='/leads')return <LeadsPage navigate={navigate}/>
 if(route==='/clients')return <ClientsPage navigate={navigate}/>
 if(route==='/projects')return <ProjectsPage/>
 if(route==='/documents')return <DocumentsPage/>
 if(route==='/activity')return <ActivityPage/>
 if(route==='/notifications')return <NotificationsPage/>
 return <AdminOverview profile={profile} navigate={navigate}/>
}

export default function App(){
 const initialHash=useMemo(()=>new URLSearchParams(location.hash.replace(/^#/,'')),[])
 const initialAuthType=initialHash.get('type')
 const initialCode=useMemo(()=>new URLSearchParams(location.search).get('code'),[])
 const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[membership,setMembership]=useState<Membership|null>(null),[profile,setProfile]=useState<Profile|null>(null),[route,setRoute]=useState(path()),[passwordFlow,setPasswordFlow]=useState(false),[authLinkError,setAuthLinkError]=useState(''),[mobileNav,setMobileNav]=useState(false)
 useEffect(()=>{const pop=()=>{setRoute(path());setMobileNav(false)};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[])
 useEffect(()=>{
  let alive=true
  const boot=async()=>{
   if(route==='/set-password'){
    const accessToken=initialHash.get('access_token'),refreshToken=initialHash.get('refresh_token')
    if((initialAuthType==='recovery'||initialAuthType==='invite')&&accessToken&&refreshToken){
     const{data,error}=await supabase.auth.setSession({access_token:accessToken,refresh_token:refreshToken})
     if(!alive)return
     if(error){setAuthLinkError(error.message);setLoading(false);return}
     setPasswordFlow(true);setSession(data.session);setLoading(false);return
    }
    if(initialCode){
     const{data,error}=await supabase.auth.exchangeCodeForSession(initialCode)
     if(!alive)return
     if(error){setAuthLinkError(error.message);setLoading(false);return}
     setPasswordFlow(true);setSession(data.session);setLoading(false);return
    }
   }
   const{data}=await supabase.auth.getSession()
   if(alive){setSession(data.session);setLoading(false)}
  }
  boot()
  const{data:{subscription}}=supabase.auth.onAuthStateChange((event,s)=>{if(event==='PASSWORD_RECOVERY')setPasswordFlow(true);setSession(s);if(!s){setMembership(null);setProfile(null)}})
  return()=>{alive=false;subscription.unsubscribe()}
 },[])
 useEffect(()=>{if(!session)return;Promise.all([supabase.from('app_memberships').select('role,status').eq('user_id',session.user.id).maybeSingle(),supabase.from('profiles').select('full_name,email').eq('id',session.user.id).maybeSingle()]).then(([m,p])=>{setMembership(m.data as Membership|null);setProfile(p.data as Profile|null)})},[session])
 const active=useMemo(()=>membership?.status==='active'?membership:null,[membership])
 const navigate=(p:string)=>{history.pushState({},'',p);setRoute(p)}
 if(loading)return <main className="loading"><Brand/><span>Opening workspace…</span></main>
 if(route==='/set-password'&&(!passwordFlow||!session))return <main className="pending"><Brand/><p className="eyebrow">Secure password setup</p><h1>{authLinkError?'This password link could not be opened.':"This password link isn't active."}</h1><p>{authLinkError?'The link may have expired or already been used. Request a fresh password email and try again.':'For your protection, a password can only be changed from the recovery or invitation link sent to that account.'}</p><button className="primary" onClick={async()=>{await supabase.auth.signOut();history.replaceState({},'','/');location.reload()}}>Return to sign in</button></main>
 if(!session)return <Login/>
 if(route==='/set-password')return <SetPassword/>
 if(!active)return <PendingAccess email={session.user.email}/>
 return <div className="app-shell"><header className="mobile-bar"><Brand/><button className="mobile-menu-button" aria-label="Open navigation" aria-expanded={mobileNav} onClick={()=>setMobileNav(v=>!v)}>Menu</button></header>{mobileNav&&<button className="mobile-scrim" aria-label="Close navigation" onClick={()=>setMobileNav(false)}/>}<Sidebar role={active.role} current={route} navigate={navigate} mobileOpen={mobileNav} onNavigate={()=>setMobileNav(false)} onSignOut={()=>supabase.auth.signOut()}/><main className="workspace">{active.role==='client'?<ClientRouter route={route} profile={profile} navigate={navigate}/>:<AdminRouter route={route} profile={profile} navigate={navigate}/>}</main></div>
}
