import { FormEvent,useEffect,useMemo,useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { supabase } from './lib/supabase'
type Membership={role:'owner'|'admin'|'staff'|'client';status:'invited'|'active'|'suspended'}
type Profile={full_name:string|null;email:string|null}
type Inquiry={id:string;name:string;email:string;company:string|null;project_type:string;status:string;created_at:string}
const stages=['Inquiry','Discovery','Proposal','Contract','Kickoff','Build','Launch']
function Brand(){return <a className="brand" href="/" aria-label="SRCcvde workspace"><span>SRC</span>cvde<i/></a>}
function Login(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const{error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setMessage(error.message)}async function reset(){if(!email){setMessage('Enter your email first.');return}setBusy(true);const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:'https://app.srccvde.com/'});setBusy(false);setMessage(error?error.message:'Password reset email sent.')}return <main className="auth-page"><section className="auth-copy"><Brand/><p className="eyebrow">SRCcvde Workspace</p><h1>Your project has a home.</h1><p>One secure place for progress, documents, approvals, change requests and everything we build together.</p><div className="stage-preview">{stages.map((s,i)=><div key={s}><b>{String(i+1).padStart(2,'0')}</b><span>{s}</span></div>)}</div></section><section className="auth-panel"><form onSubmit={submit}><p className="eyebrow">Private access</p><h2>Welcome back.</h2><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><button className="text-button" type="button" onClick={reset} disabled={busy}>Forgot password?</button>{message&&<p className="form-message" role="status">{message}</p>}<p className="fine">Accounts are created by SRCcvde. Project applicants receive access when their workspace is ready.</p></form></section></main>}
function Sidebar({role,onSignOut}:{role:Membership['role'];onSignOut:()=>void}){const admin=role!=='client';const items=admin?['Overview','Leads','Clients','Projects','Documents','Activity']:['Overview','Project','Documents','Requests','Activity'];return <aside className="sidebar"><Brand/><nav>{items.map((x,i)=><button className={i===0?'active':''} key={x}><span>{x.slice(0,1)}</span>{x}</button>)}</nav><div className="sidebar-bottom"><small>{admin?'SRCcvde team':'Client workspace'}</small><button onClick={onSignOut}>Sign out</button></div></aside>}
function ApplicantTimeline(){return <section className="timeline-card"><div className="section-head"><div><p className="eyebrow">Your journey</p><h2>Application received</h2></div><span className="status">In review</span></div><div className="timeline">{stages.slice(0,5).map((s,i)=><div className={i===0?'current':''} key={s}><i/><b>{s}</b><small>{i===0?'We have your brief':i===1?'Next step':'Upcoming'}</small></div>)}</div></section>}
function AdminDashboard({profile}:{profile:Profile|null}){const[inquiries,setInquiries]=useState<Inquiry[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{let live=true;(async()=>{const{data}=await supabase.from('project_inquiries').select('id,name,email,company,project_type,status,created_at').order('created_at',{ascending:false}).limit(6);if(live){setInquiries((data||[]) as Inquiry[]);setLoading(false)}})();return()=>{live=false}},[]);const first=profile?.full_name?' '+profile.full_name.split(' ')[0]:'';return <><header className="topbar"><div><p className="eyebrow">Command center</p><h1>Good to see you{first}.</h1></div><span className="live-dot">Live workspace</span></header><section className="metric-grid"><article><small>New inquiries</small><strong>{loading?'—':inquiries.filter(x=>x.status==='new').length}</strong><span>recent queue</span></article><article><small>Active clients</small><strong>—</strong><span>unlocks in phase 2</span></article><article><small>Active projects</small><strong>—</strong><span>unlocks in phase 2</span></article><article><small>Needs attention</small><strong>—</strong><span>approvals + requests</span></article></section><section className="panel"><div className="section-head"><div><p className="eyebrow">CRM</p><h2>Latest inquiries</h2></div><span className="status">{inquiries.length} shown</span></div>{loading?<p className="muted">Loading inquiries…</p>:inquiries.length===0?<p className="muted">No inquiries yet.</p>:<div className="lead-list">{inquiries.map(x=><article key={x.id}><div className="avatar">{x.name.slice(0,2).toUpperCase()}</div><div><b>{x.name}</b><small>{x.company||x.email}</small></div><span>{x.project_type}</span><em>{x.status}</em></article>)}</div>}</section></>}
function ClientDashboard({profile}:{profile:Profile|null}){const first=profile?.full_name?' '+profile.full_name.split(' ')[0]:'';return <><header className="topbar"><div><p className="eyebrow">Client workspace</p><h1>Welcome{first}.</h1></div><span className="live-dot">Secure workspace</span></header><ApplicantTimeline/><section className="two-col"><article className="panel"><p className="eyebrow">Next step</p><h2>We're reviewing your project.</h2><p className="muted">When SRCcvde advances your application, this workspace will grow with your project—without another account or another portal.</p></article><article className="panel"><p className="eyebrow">Documents</p><h2>Nothing needed yet.</h2><p className="muted">Contracts, scope, approvals and deliverables will appear here when they're ready for you.</p></article></section></>}
function PendingAccess({email}:{email?:string}){return <main className="pending"><Brand/><p className="eyebrow">Workspace access</p><h1>You're signed in.</h1><p>{email} does not have an active SRCcvde workspace membership yet.</p><button className="primary" onClick={()=>supabase.auth.signOut()}>Sign out</button></main>}
export default function App(){const[session,setSession]=useState<Session|null>(null);const[loading,setLoading]=useState(true);const[membership,setMembership]=useState<Membership|null>(null);const[profile,setProfile]=useState<Profile|null>(null);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(!s){setMembership(null);setProfile(null)}});return()=>subscription.unsubscribe()},[]);useEffect(()=>{if(!session)return;Promise.all([supabase.from('app_memberships').select('role,status').eq('user_id',session.user.id).maybeSingle(),supabase.from('profiles').select('full_name,email').eq('id',session.user.id).maybeSingle()]).then(([m,p])=>{setMembership(m.data as Membership|null);setProfile(p.data as Profile|null)})},[session]);const active=useMemo(()=>membership?.status==='active'?membership:null,[membership]);if(loading)return <main className="loading"><Brand/><span>Opening workspace…</span></main>;if(!session)return <Login/>;if(!active)return <PendingAccess email={session.user.email}/>;return <div className="app-shell"><Sidebar role={active.role} onSignOut={()=>supabase.auth.signOut()}/><main className="workspace">{active.role==='client'?<ClientDashboard profile={profile}/>:<AdminDashboard profile={profile}/>}</main></div>}
