-- Operational notification outbox and workflow triggers.
-- Applied to production as migration: wire_operational_notification_outbox
-- Source of truth for notification categories and recipient routing.
create table if not exists public.notification_outbox (
 id uuid primary key default gen_random_uuid(),
 recipient_user_id uuid not null references auth.users(id) on delete cascade,
 category text not null check (category in ('project_updates','documents','approvals','messages','billing','security','marketing')),
 title text not null, body text not null, url text not null default '/', tag text,
 status text not null default 'pending' check (status in ('pending','processing','sent','skipped','failed')),
 attempts integer not null default 0, last_error text,
 created_at timestamptz not null default now(), processed_at timestamptz
);
create index if not exists notification_outbox_pending_idx on public.notification_outbox(status,created_at);
alter table public.notification_outbox enable row level security;
revoke all on public.notification_outbox from anon, authenticated;
create or replace function private.enqueue_client_notification(p_client uuid,p_category text,p_title text,p_body text,p_url text,p_tag text) returns void language sql security definer set search_path=public,private as $ insert into public.notification_outbox(recipient_user_id,category,title,body,url,tag) select distinct cm.user_id,p_category,p_title,p_body,p_url,p_tag from public.client_memberships cm join public.app_memberships am on am.user_id=cm.user_id where cm.client_id=p_client and am.status='active'; $;
create or replace function private.enqueue_staff_notification(p_category text,p_title text,p_body text,p_url text,p_tag text) returns void language sql security definer set search_path=public,private as $ insert into public.notification_outbox(recipient_user_id,category,title,body,url,tag) select user_id,p_category,p_title,p_body,p_url,p_tag from public.app_memberships where status='active' and role in ('owner','admin','staff'); $;
create or replace function private.notify_signature_request() returns trigger language plpgsql security definer set search_path=public,private as $ begin if new.signer_side='client' then perform private.enqueue_client_notification(new.client_id,'documents',case when new.signature_kind='acknowledgment' then 'Document ready to acknowledge' else 'Signature requested' end,new.signer_name||', a document is ready in your SRCcvde workspace.','/documents/'||new.id,'document-'||new.id); end if; return new; end $;
drop trigger if exists trg_notify_signature_request on public.signature_requests; create trigger trg_notify_signature_request after insert on public.signature_requests for each row execute function private.notify_signature_request();
create or replace function private.notify_signature_completed() returns trigger language plpgsql security definer set search_path=public,private as $ begin if old.status is distinct from new.status and new.status='signed' and new.signer_side='client' then perform private.enqueue_staff_notification('approvals','Client document completed',new.signer_name||' completed a document action.','/clients/'||new.client_id,'signed-'||new.id); end if; return new; end $;
drop trigger if exists trg_notify_signature_completed on public.signature_requests; create trigger trg_notify_signature_completed after update of status on public.signature_requests for each row execute function private.notify_signature_completed();
create or replace function private.notify_document_final() returns trigger language plpgsql security definer set search_path=public,private as $ begin if old.state is distinct from new.state and new.state='final' and new.client_visible then perform private.enqueue_client_notification(new.client_id,'documents','Document fully executed',new.name||' is fully executed and available in your workspace.','/documents','final-'||new.id); end if; return new; end $;
drop trigger if exists trg_notify_document_final on public.client_documents; create trigger trg_notify_document_final after update of state on public.client_documents for each row execute function private.notify_document_final();
create or replace function private.notify_project_change() returns trigger language plpgsql security definer set search_path=public,private as $ begin if old.phase is distinct from new.phase or old.status is distinct from new.status or old.progress is distinct from new.progress then perform private.enqueue_client_notification(new.client_id,'project_updates','Project update',new.name||' is now in '||replace(new.phase,'_',' ')||' · '||new.progress||'% complete.','/project','project-'||new.id); end if; return new; end $;
drop trigger if exists trg_notify_project_change on public.projects; create trigger trg_notify_project_change after update of phase,status,progress on public.projects for each row execute function private.notify_project_change();
create or replace function private.notify_milestone_change() returns trigger language plpgsql security definer set search_path=public,private as $ declare cid uuid; begin if new.client_visible and old.status is distinct from new.status then select client_id into cid from public.projects where id=new.project_id; perform private.enqueue_client_notification(cid,'project_updates','Milestone updated',new.title||' is now '||replace(new.status,'_',' ')||'.','/project','milestone-'||new.id); end if; return new; end $;
drop trigger if exists trg_notify_milestone_change on public.project_milestones; create trigger trg_notify_milestone_change after update of status on public.project_milestones for each row execute function private.notify_milestone_change();
create or replace function private.notify_communication() returns trigger language plpgsql security definer set search_path=public,private as $ begin if new.direction='outbound' then perform private.enqueue_client_notification(new.client_id,'messages',coalesce(new.subject,'New message from SRCcvde'),left(new.body,180),'/project','message-'||new.id); elsif new.direction='inbound' then perform private.enqueue_staff_notification('messages',coalesce(new.subject,'New client message'),left(new.body,180),'/clients/'||new.client_id,'message-'||new.id); end if; return new; end $;
drop trigger if exists trg_notify_communication on public.client_communications; create trigger trg_notify_communication after insert on public.client_communications for each row execute function private.notify_communication();
